services:
  - type: web
    name: go-scraper-api
    env: go
    buildCommand: ./build.sh
    startCommand: ./scraper-api
    envVars:
      - key: CHROME_PATH
        value: /opt/render/.chrome/chrome-linux/chrome
