services:
  - type: web
    name: go-scraper-api
    env: go
    buildCommand: ./build.sh
    startCommand: ./scraper-api
    envVars:
      - key: CHROME_PATH
        value: /usr/bin/chromium-browser
      - key: CHROMEDP_EXEC_ALLOCATOR_DEFAULT
        value: /usr/bin/chromium-browser
